src/Entity/Topic.php
<?php

namespace App\Entity;

use App\Repository\TopicRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass:TopicRepository::class)]
class Topic extends Message
{
	#[ORM\ManyToOne(targetEntity:Category::class, inversedBy:"topics")]
	#[ORM\JoinColumn(nullable:false)]
	private $category;
	
	#[ORM\Column(type:'string', length:255)]
	private $title;
	
	#[ORM\OneToMany(targetEntity:Post::class, mappedBy:"topic", orphanRemoval:true, fetch:"EAGER")]
	#[ORM\OrderBy(['id' => 'DESC'])]
	private $posts;
	
	#[ORM\Column(type:'bigint')]
	private $views;
	
	#[ORM\ManyToOne(targetEntity:User::class, inversedBy:"topics")]
	private $author;
	
	#[ORM\Column(type: 'boolean', options: ['default' => false])]
	private $locked;
	
	public function __construct()
	{
		$this->posts = new ArrayCollection();
		$this->views = 0;
		$this->locked = false;
	}
	
	public function getCategory(): ?Category
	{
		return $this->category;
	}
	
	public function setCategory(?Category $category): self
	{
		$this->category = $category;
		
		return $this;
	}
	
	public function getTitle(): ?string
	{
		return $this->title;
	}
	
	public function setTitle(string $title): self
	{
		$this->title = $title;
		
		return $this;
	}
	
	/**
	* @return Collection|Post[]
	*/
	public function getPosts(): Collection
	{
		return $this->posts;
	}
	
	public function addPost(Post $post): self
	{
		if (!$this->posts->contains($post)) {
			$this->posts[] = $post;
			$post->setTopic($this);
		}
		
		return $this;
	}
	
	public function removePost(Post $post): self
	{
		if ($this->posts->removeElement($post)) {
			// set the owning side to null (unless already changed)
			if ($post->getTopic() === $this) {
				$post->setTopic(null);
			}
		}
		
		return $this;
	}
	
	public function increaseView(): void
	{
		$this->views++;
	}
	
	public function getViews(): ?string
	{
		return $this->views;
	}
	
	public function setViews(string $views): self
	{
		$this->views = $views;
		
		return $this;
	}
	
	public function getLastPost(): ?Post
	{
		return $this->posts->count() ? $this->posts->last() : null;
	}
	
	public function getAuthor(): ?User
	{
		return $this->author;
	}
	
	public function setAuthor(?User $author): self
	{
		$this->author = $author;
		
		return $this;
	}
	
	public function isLocked(): ?bool
	{
		return $this->locked;
	}
	
	public function setLocked(bool $locked): self
	{
		$this->locked = $locked;
		
		return $this;
	}
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Symfofo {% block title %}{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	
	{{ encore_entry_link_tags('app') }}
	{% block stylesheets %}{% endblock %}
	
	{{ encore_entry_script_tags('app') }}
	{% block javascripts %}	{% endblock %}
</head>
<body>
	<div class="ui fixed inverted menu">
		<div class="ui container">
			<a href="#" class="item header">
				Symfofo
			</a>
			
			<a  href="{{ path('app') }}" class="item">
				Forums
			</a>
			<div class="right menu">
				{% if app.user %}
				{% if is_granted("ROLE_MOD") %}
				<div class="ui simple dropdown item right">
					<em class="fa-solid fa-wrench" aria-hidden="true"></em> Administration <em class="dropdown icon"></em>
					<div class="menu">
						<a class="item" href="{{ path('app_admin_user') }}">
							<em class="fa-solid fa-users"></em>
							{{ 'manage_users'|trans }}
						</a>
						{% if is_granted("ROLE_ADMIN") %}
						<a class="item" href="{{ path('app_admin_category') }}">
							<em class="fa-solid fa-folder"></em>
							{{ 'manage_categories'|trans }}
						</a>
						{% endif %}
					</div>
				</div>
				{% endif %}
				<a class="item" href="{{ path('app_profile') }}">
					<em class="fa-solid fa-user"></em>
					{{ 'profile'|trans }}
				</a>
				
				<a class="item" href="{{ path('app_account') }}">
					<em class="fa-solid fa-gear"></em>
					{{ 'account'|trans }}
				</a>
				
				<a href="{{ path('app_search') }}" class="item right">
					<em class="fa-solid fa-search"></em>
					{{ 'search'|trans }}
				</a>
				
				<a href="{{ path('app_logout') }}" class="item right">
					<em class="fa-solid fa-right-from-bracket"></em>
					{{ 'logout'|trans }}
				</a>
				{% else %}
				<a href="{{ path('app_search') }}" class="item right">
					<em class="fa-solid fa-search"></em>
					{{ 'search'|trans }}
				</a>
				
				<a href="{{ path('app_registration') }}" class="item right">
					<em class="fa-solid fa-user-plus"></em>
					{{ 'register'|trans }}
				</a>
				
				<a href="{{ path('app_login') }}" class="item right">
					<em class="fa-solid fa-right-from-bracket"></em>
					{{ 'login'|trans }}
				</a>
				{% endif %}
				
				<div class="ui simple dropdown item right">
					<em class="fa-solid fa-language" aria-hidden="true"></em>
					<div class="menu">
						<a class="item" href="{{ path('app_language', {'locale': 'en'}) }}">
							EN
						</a>
						<a class="item" href="{{ path('app_language', {'locale': 'fr'}) }}">
							FR
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<div class="ui segment container main">
		{% block body %}{% endblock %}
	</div>
	
	<div class="ui segment container">
		{{ render(controller('App\\Controller\\IndexController::online')) }}
	</div>
</body>
</html>

templates/category.html.twig
{% extends 'base.html.twig' %}

{% block title %}- {{ category.name }}{% endblock %}

{% block stylesheets %}
{{ encore_entry_link_tags('category') }}
{% endblock %}

{% block javascripts %}
{{ encore_entry_script_tags('category') }}
{% endblock %}

{% block body %}
<p class="ui header">Forum</p>

<h1 class="ui top attached header inverted">
    {{ category.name }}
</h1>

<div class="ui attached segment">
    {% for topic in topics %}
    <div class="ui grid stackable topic">
        <div class="one wide column middle aligned">
            <div class="ui fluid image small">
                <img src="{{ asset('build/images/square-image.png') }}" alt="Default topic picture">
            </div>
        </div>
        <div class="six wide column">
            <div class="row">
                <a href="{{ path('app_topic', {'id': topic.id}) }}">
                    {{ topic.title }}
                </a>
            </div>
            <div class="row">
                {{ topic.createdAt|format_datetime('medium', 'short', locale=app.request.locale)}}
            </div>
            <div class="row">
                {{ topic.author.username }}
            </div>
        </div>
        <div class="two wide column middle aligned">
            <div class="row">{{ topic.views }}</div>
            <div class="row">
                <strong>{{ 'views'|trans }}</strong>
            </div>
        </div>
        <div class="four wide column middle aligned">
            <div class="row">{{ topic.posts|length }}</div>
            <div class="row">
                <strong>{{ 'posts'|trans }}</strong>
            </div>
        </div>
        {% if topic.lastPost %}
        <div class="three wide column right aligned middle aligned">
            <div class="row">
                <strong>
                    {{ topic.lastPost.author.username }}
                </strong>
            </div>
            <div class="row">
                {{ topic.lastPost.createdAt|format_datetime('medium', 'short', locale=app.request.locale)}}
            </div>
        </div>
        {% endif %}
    </div>
    {% endfor %}
    
    <div class="ui grid stackable">
        <div class="sixteen wide column">
            {% if app.user %}
            <a class="ui button right floated" href="{{ path('app_topic_new', {'id': category.id}) }}">
                {{ 'new_topic'|trans }}
            </a>
            {% endif %}
        </div>
    </div>

    {% if category.topics|length > 10 %}
    <div class="ui pagination menu">
        {% for i in 1..(topics|length / 10)|round(0, 'ceil') %}
        <a class="item {% if i == currentPage %}active{% endif %}" href="{{ path('app_category', {'id': category.id, 'page': i}) }}">
            {{ i }}
        </a>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
<p class="ui header">Forum</p>

{% for category in categories %}
<div class="category">
	<h4 class="ui top attached header inverted">
		<div class="ui grid stackable">
			<div class="wide column">
				{{ category.name }}
			</div>
		</div>
	</h4>
	{% for subCategory in category.categories %}
	<div class="ui attached segment">
		<div class="ui grid stackable">
			<div class="two wide column">
				<div class="ui fluid image tiny">
					<img src="{{ asset('build/images/square-image.png') }}" alt="Default category picture">
				</div>
			</div>
			<div class="four wide column">
				<div class="row">
					<h5>
						<a href="{{ path('app_category', {'id': subCategory.id}) }}">{{ subCategory.name }}</a>
					</h5>
				</div>
				<div class="row">
					{{ subCategory.description }}
				</div>
			</div>
			<div class="one wide column"></div>
			<div class="sixteen wide mobile eight wide tablet three wide computer column">
				<div class="row">{{ subCategory.topics|length }}</div>
				<div class="row">{{ 'topics'|trans }}</div>
			</div>
			<div class="sixteen wide mobile eight wide tablet three wide computer column">
				<div class="row">{{ subCategory.posts|length }}</div>
				<div class="row">{{ 'posts'|trans }}</div>
			</div>
			<div class="three wide column right aligned">
				<div class="row">
					<a href="{{ path('app_topic', {'id': subCategory.topics|last.id}) }}">
						{{ subCategory.topics|last.title|length > 50 ? subCategory.topics|last.title|slice(0, 50) ~ '...' : subCategory.topics|last.title  }}
					</a>
				</div>
				<div class="row">
					<b>{{ subCategory.topics|last.author.username }}</b>
				</div>
				<div class="row">
					<small>
						{{ subCategory.topics|last.createdAt|format_datetime('medium', 'short', locale=app.request.locale) }}
					</small>
				</div>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
{% endfor %}
{% endblock %}

templates/online.html.twig
<div class="ui" id="online-users">
	<div class="header">
		{{ 'online_users'|trans }}
	</div>
	<div class="content">
		{% if users|length %}
		<p>{{ 'online_user'|trans({'%users%': users|length}) }}</p>
		{% else %}
		<p>{{ 'no_online_user'|trans }}</p>
		{% endif %}
		<p>
			{% for user in users %}
			<span 
			{% if 'ROLE_MOD' in user.roles %}
			class="mod"
			{% elseif 'ROLE_ADMIN' in user.roles %}
			class="admin"
			{% elseif 'ROLE_SUPER_ADMIN' in user.roles %}
			class="super-admin"
			{% else %}
			class="user"
			{% endif %}
			>
			{{ user.username }}
		</span>
		{% if user != users|last %},{% endif %}
		{% endfor %}
	</p>
</div>
</div>

templates/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}- {{ 'profile'|trans }}{% endblock %}

{% block stylesheets %}
{{ encore_entry_link_tags('profile') }}
{% endblock %}

{% block body %}
<h1>{{ 'profile'|trans }}</h1>

{{ form_start(form, {'attr': {'class': 'ui form'}}) }}
{{ form_widget(form.profile_picture) }}
{% if app.user.profilePictureFilename %}
<img src="{{ asset('uploads/profil/' ~ app.user.profilePictureFilename) }}" alt="">
{% endif %}
{{ form_widget(form.delete_profile_picture) }}
{{ form_widget(form.signature) }}
{% for message in app.flashes('success') %}
<div class="ui positive message transition">
    <p>{{ message }}</p>
</div>
{% endfor %}
{% for message in app.flashes('error') %}
<div class="ui negative message transition">
    <p>{{ message }}</p>
</div>
{% endfor %}
{{ form_end(form) }}
{% endblock %}